apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: myapp-pod
      namespace: dev  
      labels:             
        app: myapp
        type: front-end
    spec:             
      containers:                
        - name: nginx-container
          image: nginx