apiVersion: batch/v1
kind: Job
metadata:
  name: match-add-job
spec:
  #completions: 3
  #parallelism: 3
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr', '3', '+', '2']
      restartPolicy: Never

# $ kubectl get jobs
# $ kubectl get pods
# $ kubectl logs math-add-job-1d78pn
    # To see the output of math operation.