apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce           # ReadOnlyMany # ReadWriteOnce # ReadWriteMany
  capacity:
    storage: 1Gi
  #hostPath:
    #path: /tmp/data           # not to be used in production environment
  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4