# administrator creates persistent volumes and user creates persistent volume claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

# persistentVolumeReclaimPolicy: Retain or Delete or Recycle